### ISSUE TITLE
Autoincrementos?

### ISSUE THREAD

**Issue by DanBaDo** [JuanJoseGitHub/supermegacontador#2]
En la siguiente linea haces una cosa curiosa, al igual que en la 15
https://github.com/JuanJoseGitHub/supermegacontador/blob/df0c16ddb4caaef8f96b2367150dea7b13d3046a/src/App.js#L11

Los operadores `++` y `--` cambian el valor de la variable a la que afectan, asignandole el resultado de sumar o restar un respectivamente. En nuestro caso, no estamos trabajando con una variable puramente, sino que se trata de un state de React. La asignación no debemos de hacerla de forma directa, sino empleando un setter, __como bien estas haciendo__.

Pero eso hace que usar el operador de auto incremento sea algo curioso. Produce un poco de "ruido" cuando leemos el código. A mi modo de ver, aunque funciona tal y como lo tienes, sería preferible usar la forma: `setValor(valor+1)`

**Comment by DanBaDo** [comment]
P.D: Por lo demás ¡Genial! 👍

**Comment by JuanJoseGitHub** [comment]
Ola Dani:
Correxidos ambas observacións, a do CSS, que o puxen no CSS global (App.css) e o tema do preincremento, que o substituin por unha asignación "tradicional".
Moitas grazas .

Juan José Hidalgo Neira.



Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: Daniel Bañobre Dopico ***@***.***>
Enviado: viernes, 3 de marzo de 2023 20:40
Para: JuanJoseGitHub/supermegacontador ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [JuanJoseGitHub/supermegacontador] Autoincrementos? (Issue #2)


En la siguiente linea haces una cosa curiosa, al igual que en la 15
https://github.com/JuanJoseGitHub/supermegacontador/blob/df0c16ddb4caaef8f96b2367150dea7b13d3046a/src/App.js#L11<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJuanJoseGitHub%2Fsupermegacontador%2Fblob%2Fdf0c16ddb4caaef8f96b2367150dea7b13d3046a%2Fsrc%2FApp.js%23L11&data=05%7C01%7C%7C44e4b6ef1ec548d8cbf008db1c1f3621%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638134692589972620%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=N6G6gSgjdu6vsUHfyzYq5MVErLrA579YIRoi7g6ZY3s%3D&reserved=0>

Los operadores ++ y -- cambian el valor de la variable a la que afectan, asignandole el resultado de sumar o restar un respectivamente. En nuestro caso, no estamos trabajando con una variable puramente, sino que se trata de un state de React. La asignación no debemos de hacerla de forma directa, sino empleando un setter, como bien estas haciendo.

Pero eso hace que usar el operador de auto incremento sea algo curioso. Produce un poco de "ruido" cuando leemos el código. A mi modo de ver, aunque funciona tal y como lo tienes, sería preferible usar la forma: setValor(valor+1)

**Comment by DanBaDo** [comment]
Lembra pechar os issue!
